create table USERS
(
ID NUMBER NOT NULL,
CONSTRAINT USERS_PK PRIMARY KEY (ID),
FIRST_NAME NVARCHAR2(15) NOT NULL,
LAST_NAME NVARCHAR2(15) NOT NULL,
EMAIL NVARCHAR2(20) NOT NULL,
PHONE NVARCHAR2(20) NOT NULL,
IS_EMAIL_VERIFIED NUMBER NOT NULL,
IS_PHONE_VERIFIED NUMBER NOT NULL,
DATE_OF_BIRTH DATE NOT NULL,
CITY NVARCHAR2(20) NOT NULL,
ADS_PUBLISHED_ID NUMBER,
ADS_JOINED_ID NUMBER,
RATING NUMBER,
ATTRIBUTES CLOB,
FRIENDS NUMBER,
LAST_LOGIN DATE,
DATE_REGISTERED DATE,
IS_ACTIVE NUMBER NOT NULL,

CONSTRAINT FRIENDS_ID_FK FOREIGN KEY (ADS_PUBLISHED_ID) REFERENCES
USERS(ID),
CONSTRAINT ADS_PUBLISHED_ID_FK FOREIGN KEY (ADS_PUBLISHED_ID) REFERENCES
AD(ID),
CONSTRAINT ADS_JOINED_ID_FK FOREIGN KEY (ADS_JOINED_ID) REFERENCES
AD(ID)

);

CREATE SEQUENCE USERS_SEQ MINVALUE 1000 MAXVALUE 10000000000 START WITH 1001 INCREMENT BY 1;

ALTER TABLE USERS
DROP COLUMN ADS_PUBLISHED_ID;

ALTER TABLE USERS
DROP COLUMN ADS_JOINED_ID;

ALTER TABLE USERS
ADD FRIEND_ID

ALTER TABLE USERS
CONSTRAINT FRIENDS_FK

ALTER TABLE USERS
ADD CONSTRAINT FRIEND_ID_FK FOREIGN KEY (FRIEND_ID) REFERENCES USERS(ID);