CREATE TABLE AD
(
ID NUMBER NOT NULL,
CONSTRAINT AD_PK PRIMARY KEY (ID),
CREATOR_ID NUMBER NOT NULL,
USER_ID NUMBER,

CONSTRAINT CREATOR_ID_FK FOREIGN KEY (CREATOR_ID ) REFERENCES
USERS(ID),
CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES
USERS(ID)
);

CREATE SEQUENCE AD_SEQ MINVALUE 1000 MAXVALUE 10000000000 START WITH 1001 INCREMENT BY 1;