CREATE TABLE AD
(
ID NUMBER NOT NULL,
CONSTRAINT AD_PK PRIMARY KEY (ID),
ITEM_NAME NVARCHAR2(30) NOT NULL,
TOTAL_PRICE NVARCHAR2(30) NOT NULL,
CITY NVARCHAR2(30) NOT NULL,
DATE_EXPIRES TIMESTAMP NOT NULL,
DATE_CREATED TIMESTAMP NOT NULL,
DATE_EDITED TIMESTAMP,
IS_ACTIVE NUMBER NOT NULL,

OWNER_ID NUMBER NOT NULL,
PARTICIPANTS_ID NUMBER,

CONSTRAINT CREATOR_ID_FK FOREIGN KEY (OWNER_ID) REFERENCES
USERS(ID),
CONSTRAINT USER_ID_FK FOREIGN KEY (PARTICIPANTS_ID) REFERENCES
USERS(ID)
);

CREATE SEQUENCE AD_SEQ MINVALUE 1000 MAXVALUE 10000000000 START WITH 1001 INCREMENT BY 1;