DECLARE
    counter INTEGER := 0;
--    random_numb INTEGER := FLOOR(RAND(CHECKSUM(NEWID()))*(9999-1000)+1000);
    random_owner_id INTEGER := 1102;
BEGIN
  WHILE counter < 1000000
  LOOP
    INSERT INTO AD (ID, ITEM_NAME, TOTAL_PRICE, CITY, DATE_EXPIRES, DATE_CREATED, DATE_EDITED, IS_ACTIVE, OWNER_ID, PARTICIPANTS_ID)
    VALUES(counter, 'TEST_ITEM', counter, 'kiev', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, random_owner_id, 1121);
     counter := counter + 1;
  END LOOP;
END;

DELETE FROM AD;