CREATE TABLE AD_PARTICIPANTS (
AD_ID NUMBER NOT NULL,
USER_ID NUMBER NOT NULL,
PRIMARY KEY (AD_ID, USER_ID),
CONSTRAINT AD_ID_FK FOREIGN KEY(AD_ID) REFERENCES AD(ID),
CONSTRAINT USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);
-- CREATE SEQUENCE AD_PARTICIPANTS_SEQ MINVALUE 1000 MAXVALUE 10000000000 START WITH 1001 INCREMENT BY 1;