create table USERS
(
ID NUMBER NOT NULL,
CONSTRAINT USERS_PK PRIMARY KEY (ID),
FIRST_NAME NVARCHAR2(15) NOT NULL,
LAST_NAME NVARCHAR2(15) NOT NULL,
PASSWORD NVARCHAR2(15) NOT NULL,
EMAIL NVARCHAR2(20) NOT NULL,
PHONE NVARCHAR2(20) NOT NULL,
IS_EMAIL_VERIFIED NUMBER ,
IS_PHONE_VERIFIED NUMBER,
DATE_OF_BIRTH DATE NOT NULL,
CITY NVARCHAR2(20) NOT NULL,
RATING NUMBER,
ATTRIBUTES CLOB,
LAST_LOGIN DATE,
DATE_REGISTERED DATE NOT NULL,
IS_ACTIVE NUMBER
);

CREATE SEQUENCE USERS_SEQ MINVALUE 1000 MAXVALUE 10000000000 START WITH 1001 INCREMENT BY 1;