ALTER TABLE AD RENAME TO OLD_AD;
CREATE TABLE AD(
ID NUMBER NOT NULL,
PRIMARY KEY(ID),
ITEM_NAME NVARCHAR2(30) NOT NULL,
ITEMS_COUNT NUMBER NOT NULL,
PPRICE_PER_ITEM NUMBER NOT NULL,
ITEMS_RESRVED NUMBER NOT NULL,
DATE_EXPIRES TIMESTAMP NOT NULL,
DATE_CREATED TIMESTAMP NOT NULL,
DATE_EDITED TIMESTAMP,
IS_ACTIVE NUMBER NOT NULL,
OWNER_ID NUMBER NOT NULL,
CONSTRAINT CREATOR_ID_FK FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID)
)

ALTER TABLE OLD_AD
DROP CONSTRAINT CREATOR_ID_FK;
ALTER TABLE ORDERS
DROP CONSTRAINT AD_ID_FK;

DROP TABLE AD;

INSERT INTO AD
(ID, ITEM_NAME, ITEMS_COUNT, PPRICE_PER_ITEM, ITEMS_RESRVED, DATE_EXPIRES,
DATE_CREATED, DATE_EDITED, IS_ACTIVE, OWNER_ID)
SELECT ID, ITEM_NAME, TOTAL_PRICE, TOTAL_PRICE, TOTAL_PRICE, DATE_EXPIRES, DATE_CREATED,
DATE_EDITED, IS_ACTIVE, OWNER_ID FROM OLD_AD;

DROP TABLE OLD_AD;

ALTER TABLE ORDERS
ADD CONSTRAINT AD_ID_FK FOREIGN KEY(AD_ID) REFERENCES AD(ID);

ALTER TABLE AD
RENAME COLUMN ITEMS_RESRVED TO ITEMS_RESERVED;

ALTER TABLE AD
RENAME COLUMN PPRICE_PER_ITEM TO PRICE_PER_ITEM;

